apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  labels:
    app: gatekeeper
spec:
  project: default
  sources:
  - chart: "gatekeeper"
    repoURL: "https://open-policy-agent.github.io/gatekeeper/charts"
    targetRevision: 3.16.3
    helm:
      releaseName: gatekeeper
      version: v3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true