apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  labels:
    app: jenkins
spec:
  project: default
  sources:
  - chart: "jenkins"
    repoURL: "https://charts.jenkins.io"
    targetRevision: 5.1.23
    helm:
      releaseName: jenkins
      version: v3
      values: |
        controller:
          installPlugins:
          - kubernetes:4238.v41b_3ef14a_5d8
          - workflow-aggregator:596.v8c21c963d92d
          - git:5.2.2
          - configuration-as-code:1850.va_a_8c31d3158b_
          - blueocean:1.27.12
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
